# TEAM PAMBACODE

# ESTE CÓDIGO MUESTRA UN EJEMPLO DEL USO DEL CICLO FOR
#EL CICLO O FUNCION FOR SIRVE PARA REALIZAR REPETIDAMENTE (ITERAR) UN CONJUNTO ACCIONES (QUE SE
#DEFINEN DENTRO DEL CICLO) SOBRE UNA LISTA, DICCIONARIO O UNA CADENA DE TEXTO.
#SE DEFINE EL NOMBRE QUE TENDRA CADA ELEMENTO DE LA LISTA O SECUENCIA A LA HORA DE DEFINIR UN CICLO FOR
# SE IMPRIMIRA EL RESULTADO PARA COMPROBAR QUE SE LA ACCION REALIZADA SI SE EJECUTO

# 2025 / 03/ 07 - V. 1. 0. 0

# TRABAJARON: CESAR ARTURO / CesarDAlvin 
#Inicio
Figuras = ["circulo", "triangulo", "cuadrado", "rectangulo"] #DEFINIMOS UNA LISTA CON ELEMENTOS A LA QUE NOMBRAREMOS "Figuras"

for Figura in Figuras: #EL CICLO FOR DEFINE CADA ELEMENTO DE LA LISTA "Figuras" COMO "Figura"
  print("Soy una figura") #SE IMPRIME UNA CADENA DE TEXTO
  print("Soy un", Figura) #SE IMPRIME UNA SIGUIENTE CADENA DE TEXTO MAS UN ELEMENTO DE LA LISTA Y EL CICLO REPITE HASTA QUE SE ACABEN LOS ELEMENTOS DE LA LISTA "Figura"
#Fin
