# TEAM PAMBACODE

# ESTE CÓDIGO MUESTRA UN EJEMPLO DEL USO DEL CICLO WHILE
# SE USA PARA REALIZAR REPETIDAMENTE UNA SECUENCIA DE ACCIONES O bLOQUE DE CODIGO HASTA
#QUE SE CUMPLA UNA CIERTA CONDICION DEFINIDA

# 2025 / 03/ 07 - V. 1. 0. 0

# TRABAJARON: CESAR ARTURO / CesarDAlvin 

#Inicio
i = 0 #SE DEFINE LA VARIABLE i COMO UN NUMERO 0

while i <= 20: #EL CICLO WHILE DICE QUE MIENTRAS EL VALOR DE i ES MENOR O IGUAL A 20 EL BLOQUE DE CODIGO SE SEGUIRA REPITIENDO
  print("Dame uno mas") #SE IMPRIME UNA CADENA DE TEXTO QUE PIDE UNO MAS, AUQNUE ES SOLO UN ADORNO
  i += 1 #SE LE SUMA 1 A LA VARIABLE i POR CADA ITERACION, ES BASICAMENTE UN CONTADOR
print("Ahi quedo nomas") #DESPUES DE CUMPLIR CON LA CONDICION IMPUESTA SE IMPRIME UNA ULTIMA CADENA DE TEXTO COMO COMFIRMACION DE QUE SE HA SALIDO DEL CICLO

#Fin
